server:
  port: 8080  # 设置端口号

  # 控制台打印
logging:
  level:
    com.*: debug
#配置mybatis
mybatis:
  # 加载mapper.xml的路劲
  mapper-locations: classpath:mapper/*.xml
  # 扫描包下的类，mybatis会使用驼峰命名自动配置别名
  type-aliases-package: com.library.bean
spring:
  # 配置数据源信息，不用多说了吧！就那些
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: wangning
    url: jdbc:mysql://localhost:3306/lsys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root


